name: "Check Flake"
on:
  workflow_dispatch:
  pull_request:
  push:
jobs:
  install-nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix flake check -Lv --allow-import-from-derivation --fallback --accept-flake-config
    - run: nix build .#ghc96-transitive-anns -Lv --fallback --accept-flake-config
    - run: nix build .#ghc98-transitive-anns -Lv --fallback --accept-flake-config
    - run: nix build .#ghc94-transitive-anns -Lv --fallback --accept-flake-config
    - run: nix build .#ghc92-transitive-anns -Lv --fallback --accept-flake-config
